Upgrade template to 3.4
scherersoftware/cakephp-app-template pull request #22
Opened 2017-07-10 13:51 UTC by cleptric

2017-07-10 19:25 UTC, felixkempf requested changes
Well done, only some minor things I would like to ask you to correct.

2017-07-10 19:25 UTC, felixkempf commented on composer.json
> +        "codekanzlei/cake-list-filter": "1.3.*",
Ich glaube im Template wäre es schon sinnvoll wenn wir die minor versions nicht locken würden, also `1.*` o.ä. verwenden würden, meinst du nicht auch?

2017-07-10 19:25 UTC, felixkempf commented on ruleset.xml
> +        <!-- checked in SchererSoftware.SlevomatCodingStandard.ControlStructures.LenientControlSignatureSniff  -->
This is not right, as the `LenientControlSignatureSniff` was removed by your hand. So this comment and the line below it references should be removed.

2017-07-10 19:25 UTC, felixkempf commented on ruleset.xml
> +        <!-- checked in SchererSoftware.SlevomatCodingStandard.ControlStructures.LenientControlSignatureSniff  -->
Although it might be that this sniff is too strict regarding the alternative `:` syntax of control structures as I told you earlier.

2017-07-10 19:25 UTC, felixkempf commented on src/Model/Table/UsersTable.php
> +            ->SetTo($user->email)
Why is Big S in the house?

2017-07-10 19:25 UTC, felixkempf commented on src/View/Helper/BootstrapFormHelper.php
> +        $input = parent::controll($field, $options);
Did you mean `control()`?

2017-07-10 19:25 UTC, felixkempf commented on src/View/Helper/PaginatorHelper.php
>  class PaginatorHelper extends \Cake\View\Helper\PaginatorHelper
Please use the Helper you extend from.

2017-07-10 19:25 UTC, felixkempf commented on tests/bootstrap.php
> +declare(strict_types = 1);
Hast du die überall anders schon hinzugefügt gehabt und nur hier vergessen? Sonst würde ich diese Zeile in sehr vielen Dateien vermissen.

2017-07-10 19:29 UTC, cleptric commented on ruleset.xml
> +        <!-- checked in SchererSoftware.SlevomatCodingStandard.ControlStructures.LenientControlSignatureSniff  -->
We can remove the whole file now.

2017-07-10 19:30 UTC, cleptric commented on tests/bootstrap.php
> +declare(strict_types = 1);
Code style checks are running on `/tests` so that's why this is fixed. Should we also cover `/config` ?

2017-07-10 19:31 UTC, cleptric commented on composer.json
> +        "codekanzlei/cake-list-filter": "1.3.*",
Not with our current versioning policy :)

2017-07-10 19:32 UTC, felixkempf commented on tests/bootstrap.php
> +declare(strict_types = 1);
sure, why not?

2017-07-10 19:33 UTC, felixkempf commented on composer.json
> +        "codekanzlei/cake-list-filter": "1.3.*",
But... but.. I can change... I **WILL** change, I promise

2017-07-11 09:02 UTC, cleptric commented on tests/bootstrap.php
> +declare(strict_types = 1);
I had to exclude config/migartions, config/Seeds and config/schema.php

2017-07-11 10:53 UTC, merged