General improvements
scherersoftware/cakephp-app-template pull request #23
Opened 2017-08-01 15:11 UTC by wolfgang-braun

- fix .env.default
- fix users view action
- fix frontend bridge instance id bug

2017-08-03 18:05 UTC, felixkempf commented on .env.default
> +
So what were the arguments for separate environment variables additional to or replacing the combined URL ones?

2017-08-03 18:06 UTC, felixkempf requested changes

2017-08-03 18:06 UTC, felixkempf commented on .env.default
> +
So what were the arguments for separate environment variables additional to or replacing the combined URL ones?

2017-08-18 06:36 UTC, cleptric commented
Thanks @wolfgang-braun I pushed some of the changes directly to master.

2017-08-18 06:36 UTC, closed without merging